require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RegistrarsController do

  # This should return the minimal set of attributes required to create a valid
  # Registrar. As you add validations to Registrar, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { :first_name=> "first", :last_name => "last", :phone =>"12345678911", :email => "zzg@cmu.edu"  }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RegistrarsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all registrars as @registrars" do
      registrar = Registrar.create! valid_attributes
      get :index, {}, valid_session
      assigns(:registrars).should eq([registrar])
    end
  end

  describe "GET show" do
    it "assigns the requested registrar as @registrar" do
      registrar = Registrar.create! valid_attributes
      get :show, {:id => registrar.to_param}, valid_session
      assigns(:registrar).should eq(registrar)
    end
  end

  describe "GET new" do
    it "assigns a new registrar as @registrar" do
      get :new, {}, valid_session
      assigns(:registrar).should be_a_new(Registrar)
    end
  end

  describe "GET edit" do
    it "assigns the requested registrar as @registrar" do
      registrar = Registrar.create! valid_attributes
      get :edit, {:id => registrar.to_param}, valid_session
      assigns(:registrar).should eq(registrar)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Registrar" do
        expect {
          post :create, {:registrar => valid_attributes}, valid_session
        }.to change(Registrar, :count).by(1)
      end

      it "assigns a newly created registrar as @registrar" do
        post :create, {:registrar => valid_attributes}, valid_session
        assigns(:registrar).should be_a(Registrar)
        assigns(:registrar).should be_persisted
      end

      it "redirects to the created registrar" do
        post :create, {:registrar => valid_attributes}, valid_session
        response.should redirect_to(Registrar.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved registrar as @registrar" do
        # Trigger the behavior that occurs when invalid params are submitted
        Registrar.any_instance.stub(:save).and_return(false)
        post :create, {:registrar => { "first_name" => "invalid value" }}, valid_session
        assigns(:registrar).should be_a_new(Registrar)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Registrar.any_instance.stub(:save).and_return(false)
        post :create, {:registrar => { "first_name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested registrar" do
        registrar = Registrar.create! valid_attributes
        # Assuming there are no other registrars in the database, this
        # specifies that the Registrar created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Registrar.any_instance.should_receive(:update_attributes).with({ "first_name" => "MyString" })
        put :update, {:id => registrar.to_param, :registrar => { "first_name" => "MyString" }}, valid_session
      end

      it "assigns the requested registrar as @registrar" do
        registrar = Registrar.create! valid_attributes
        put :update, {:id => registrar.to_param, :registrar => valid_attributes}, valid_session
        assigns(:registrar).should eq(registrar)
      end

      it "redirects to the registrar" do
        registrar = Registrar.create! valid_attributes
        put :update, {:id => registrar.to_param, :registrar => valid_attributes}, valid_session
        response.should redirect_to(registrar)
      end
    end

    describe "with invalid params" do
      it "assigns the registrar as @registrar" do
        registrar = Registrar.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Registrar.any_instance.stub(:save).and_return(false)
        put :update, {:id => registrar.to_param, :registrar => { "first_name" => "invalid value" }}, valid_session
        assigns(:registrar).should eq(registrar)
      end

      it "re-renders the 'edit' template" do
        registrar = Registrar.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Registrar.any_instance.stub(:save).and_return(false)
        put :update, {:id => registrar.to_param, :registrar => { "first_name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested registrar" do
      registrar = Registrar.create! valid_attributes
      expect {
        delete :destroy, {:id => registrar.to_param}, valid_session
      }.to change(Registrar, :count).by(-1)
    end

    it "redirects to the registrars list" do
      registrar = Registrar.create! valid_attributes
      delete :destroy, {:id => registrar.to_param}, valid_session
      response.should redirect_to(registrars_url)
    end
  end

end
